version: 2.0
jobs:
  build:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: npm install
      - run: node index.js -a Dehradun --gapi_key AIzaSyBYymoF_SrKoyMG01Sq_JRM71TtAVSxpU8 --dapi_key 8c84e2eb178a6b650e1f8895406e1998