version: 2.0
jobs:
  build:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run:
          name: Install npm 
          command: npm install
      - add_ssh_keys:
          fingerprints:
            - "05:74:84:21:d3:a9:a7:bb:7a:a7:5d:d8:7b:64:82:a3"    
      - run:
          name: Execute Index.js 
          command: node index.js -a Dehradun --gapi_key $GAPI_KEY --dapi_key $DAPI_KEY
      - run: 
          name: Auth With NPM
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
      - run:
          name: Publish to NPM
          command: npm publish
      - run:
          name: Git email
          command: git config --global user.email "relsellglobal@gmail.com"
      - run:
          name: Git name
          command: git config --global user.name "Anil Kukreti"        
    #   - run:
    #       name: Adding Git TAG
    #       command: git tag -a 'Release_$CIRCLE_TAG' -m "Release"
    #   - run:
    #       name: Pushing Git
    #       command: git push origin tag 'Release_$CIRCLE_TAG'            